### ISSUE TITLE
Création de détails et de nouvelles compétences dans une vue.

### ISSUE THREAD

**Issue by Eragonfr** [LeCarreLibre/arbre_competences#39]
Problème:
Pour l'instant si on veut créer un détail ou une compétence il faut obligatoirement passer par le site d'administration.
Or cette méthode n'est pas efficace, ni simple pour les futurs utilisateurs.
Je propose donc la création de une ou deux pages permettant d'ajouter des détails simplement et de créer des nouvelles catégories de compétences aussi simplement que pour ajouter un utilisateur.

**Comment by Eragonfr** [comment]
Bon... On continue le projet?

**Comment by nils-van-zuijlen** [comment]
Ben... J'ai plus vraiment envie de continuer de mon côté.

**Comment by Eragonfr** [comment]
Ok, hum? Quoi comme nom?

**Comment by nils-van-zuijlen** [comment]
Ce que tu veux.

**Comment by Eragonfr** [comment]
Bon je vois ça ce soir

**Comment by Eragonfr** [comment]
https://github.com/LeCarreLibre
Le carré libre, à son GH...(non officiel)
